# Insurance Charges Prediction Using Machine Learning
This notebook loads the insurance dataset, preprocesses the data, trains multiple regression models, and compares their R² scores.

In [6]:
# Import Required Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score

In [7]:
#Load the Dataset 
df = pd.read_csv("insurance_pre.csv")

In [10]:
# Printing the dateset
df

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [8]:
# Display the Dataset
df.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [11]:
# Check Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 62.8+ KB

In [12]:
# Check Dataset Shape
print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 1338
Number of Columns : 6

In [13]:
# Check Missing Values
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [14]:
# Statistical Summary
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [15]:
# Separate Features and Target Variable
X = df.drop("charges", axis=1)
y = df["charges"]

In [16]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [17]:
# checking the first five values from dataset apart from charges
X.head()

   age     sex     bmi  children smoker
0   19  female  27.900         0    yes
1   18    male  33.770         1     no
2   28    male  33.000         3     no
3   33    male  22.705         0     no
4   32    male  28.880         0     no

In [18]:
# Display Target Variable
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [20]:
# Identify Categorical and Numerical Columns
categorical_columns = ["sex", "smoker"]
numerical_columns = ["age", "bmi", "children"]

In [21]:

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(drop="first"), categorical_columns)
    ],
    remainder="passthrough"
)

In [23]:
# Perform One-Hot Encoding
df=pd.get_dummies(df,drop_first=True)

In [24]:
df

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [26]:
# Split the Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=0
)

In [28]:
# Create Multiple Linear Regression Model
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [29]:
# Train the Model
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['sex', 'smoker'])])),
                ('regressor', LinearRegression())])

In [32]:
# Display the Bias (Intercept)
bias = model.named_steps["regressor"].intercept_

print("Bias (Intercept):")
print(bias)

Bias (Intercept):
-12113.451250916967

In [33]:
# Display the Weights
weights = model.named_steps["regressor"].coef_

print("Weights (Coefficients):")
print(weights)

Weights (Coefficients):
[-7.95178837e+00  2.36539033e+04  2.57068962e+02  3.27533514e+02
  4.27254431e+02]

In [35]:
# Display Feature Names with Their Weights
feature_names = model.named_steps["preprocessor"].get_feature_names_out()

coefficients = pd.DataFrame({
    "Feature": feature_names,
    "Weight": weights
})

coefficients

               Feature        Weight
0        cat__sex_male     -7.951788
1      cat__smoker_yes  23653.903315
2       remainder__age    257.068962
3       remainder__bmi    327.533514
4  remainder__children    427.254431

In [ ]:
# Predict the Test Data
y_pred = model.predict(X_test)

In [36]:
# Calculate the R² Score
r2 = r2_score(y_test, y_pred)

In [37]:
r2

0.7811302113434098

In [59]:
import pickle 
filename="finalized_model_linear_regression.sav"
with open(filename, "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!

In [61]:
filename = "finalized_model_linear_regression.sav"

with open(filename, "rb") as file:
    loaded_model = pickle.load(file)
    new_customer = pd.DataFrame({
    "age": [35],
    "sex": ["male"],
    "bmi": [27.5],
    "children": [2],
    "smoker": ["no"]
})
prediction = loaded_model.predict(new_customer)
print("Predicted Insurance Charges:", prediction[0])

Predicted Insurance Charges: 6737.691123712806